#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions.csv → takken-master-data-past.js（BASE_QUESTIONS を CSV 正本で上書き）。"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.csv_to_exam_site_past_js import (  # noqa: E402
    DATA_CSV,
    load_practice_questions,
    row_to_obj,
    write_practice_js,
)
from tools.site_config import category_to_field_map

CORE_JS = ROOT / "takken-master-data-core.js"
OUT_PAST_JS = ROOT / "takken-master-data-past.js"
OUT_PRACTICE_JS = ROOT / "exam-site-data-practice.js"

def write_past_js(objs: list[dict], year_labels: dict[int, str]) -> None:
    lines = [
        "/* AUTO-GENERATED by tools/csv_to_takken_master_js.py — data/past_questions.csv */",
        "const CSV_IMPORTED_YEAR_LABELS = " + json.dumps(year_labels, ensure_ascii=False) + ";",
        "const CSV_IMPORTED_PRACTICE_POOL_YEARS = [];",
        "const CSV_IMPORTED_QUESTIONS = [",
    ]
    for o in objs:
        lines.append("  " + json.dumps(o, ensure_ascii=False) + ",")
    lines.append("];")
    lines.append("")
    lines.append("if (typeof applyCsvImportedQuestions === 'function') {")
    lines.append("  applyCsvImportedQuestions();")
    lines.append("}")
    lines.append("")
    OUT_PAST_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PAST_JS} ({len(objs)} questions)")


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"Missing {DATA_CSV}", file=sys.stderr)
        return 1
    if not CORE_JS.is_file():
        print(
            f"Missing {CORE_JS}. FIELDS/SIMPLE_EXP は core に保持し、過去問のみ CSV から生成します。",
            file=sys.stderr,
        )
        return 1

    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    year_labels: dict[int, str] = {}
    for i, row in enumerate(rows, start=2):
        o = row_to_obj(row, i)
        if o is None:
            continue
        objs.append(o)
        y = o["year"]
        wl = (row.get("exam_wareki") or "").strip()
        if y not in year_labels and wl:
            year_labels[y] = wl if y > 9999 else f"{wl}（{y}年）"

    write_past_js(objs, year_labels)
    practice = load_practice_questions()
    if practice:
        write_practice_js(practice)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
