#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/glossary_terms.csv → takken-data-glossary.js（SPA 用 GLOSSARY_DATA）。"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.build_glossary_pages import glossary_field_id, norm, term_slug  # noqa: E402

GLOSSARY_CSV = ROOT / "data" / "glossary_terms.csv"
OUT_JS = ROOT / "takken-data-glossary.js"

CAT_TO_LEGACY = {
    "権利関係": "rights",
    "宅建業法": "law",
    "法令上の制限": "limit",
    "税・その他": "tax",
    "試験対策": "guide",
}


def main() -> int:
    if not GLOSSARY_CSV.is_file():
        print(f"Missing {GLOSSARY_CSV}", file=sys.stderr)
        return 1
    rows = list(csv.DictReader(GLOSSARY_CSV.read_text(encoding="utf-8-sig").splitlines()))
    used: dict[str, str] = {}
    items: list[dict] = []
    for row in rows:
        term = norm(row.get("term"))
        if not term:
            continue
        reading = norm(row.get("reading"))
        cat = norm(row.get("category"))
        slug_file = term_slug(term, reading, used)
        legacy_slug = slug_file.replace(".html", "").replace("g-", "", 1)
        if len(legacy_slug) > 20:
            legacy_slug = term.replace(" ", "-")[:40] or legacy_slug[:12]
        item: dict = {
            "id": legacy_slug.replace("-", "_")[:40] or "term",
            "cat": CAT_TO_LEGACY.get(cat, glossary_field_id(cat) or "guide"),
            "term": term,
            "reading": reading,
            "summary": norm(row.get("short_def")) or norm(row.get("definition"))[:80],
            "desc": norm(row.get("definition")) or norm(row.get("short_def")),
            "articleSlug": legacy_slug,
        }
        items.append(item)

    payload = (
        "/* AUTO-GENERATED by tools/csv_to_takken_glossary_js.py — data/glossary_terms.csv */\n"
        "const GLOSSARY_DATA = "
        + json.dumps(items, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT_JS.write_text(payload, encoding="utf-8")
    print(f"Wrote {OUT_JS} ({len(items)} terms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
