#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions.csv → takken-master-data-past.js（BASE_QUESTIONS を CSV 正本で上書き）。"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.csv_to_exam_site_past_js import (  # noqa: E402
    DATA_CSV,
    load_practice_questions,
    row_to_obj,
    write_practice_js,
)
from tools.site_config import category_to_field_map

MASTER_JS = ROOT / "takken-master-data.js"
OUT_PAST_JS = ROOT / "takken-master-data-past.js"
OUT_PRACTICE_JS = ROOT / "exam-site-data-practice.js"

CATEGORY_TO_FIELD = category_to_field_map()


def extract_block(text: str, name: str) -> str:
    """const NAME = ...; を丸ごと抜く（配列・オブジェクト対応）。"""
    m = re.search(
        rf"(const\s+{re.escape(name)}\s*=\s*(?:\{{|\[).*?;\n)",
        text,
        re.DOTALL,
    )
    return m.group(1) if m else ""


def write_core_js(text: str) -> None:
    fields = extract_block(text, "FIELDS")
    simple = extract_block(text, "SIMPLE_EXP")
    lines = [
        "/* takken-master-data-core.js — FIELDS / SIMPLE_EXP（手編集可） */",
        "/* 過去問本体は takken-master-data-past.js（data/past_questions.csv から生成） */",
        "",
        fields or "const FIELDS = [];\n",
        "",
        simple or "const SIMPLE_EXP = {};\n",
        "",
        "let BASE_QUESTIONS = [];",
        "let QUESTIONS = [];",
        "let YEARS = [];",
        "",
    ]
    core_path = ROOT / "takken-master-data-core.js"
    core_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {core_path}")


def write_past_js(objs: list[dict], year_labels: dict[int, str]) -> None:
    lines = [
        "/* AUTO-GENERATED by tools/csv_to_takken_master_js.py — data/past_questions.csv */",
        "const CSV_IMPORTED_YEAR_LABELS = " + json.dumps(year_labels, ensure_ascii=False) + ";",
        "const CSV_IMPORTED_PRACTICE_POOL_YEARS = [];",
        "const CSV_IMPORTED_QUESTIONS = [",
    ]
    for o in objs:
        lines.append("  " + json.dumps(o, ensure_ascii=False) + ",")
    lines.append("];")
    lines.append("")
    lines.append("if (typeof applyCsvImportedQuestions === 'function') {")
    lines.append("  applyCsvImportedQuestions();")
    lines.append("}")
    lines.append("")
    OUT_PAST_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PAST_JS} ({len(objs)} questions)")


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"Missing {DATA_CSV}", file=sys.stderr)
        return 1
    if not MASTER_JS.is_file():
        print(f"Missing {MASTER_JS}", file=sys.stderr)
        return 1

    legacy = MASTER_JS.read_text(encoding="utf-8")
    write_core_js(legacy)

    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    year_labels: dict[int, str] = {}
    for i, row in enumerate(rows, start=2):
        o = row_to_obj(row, i)
        if o is None:
            continue
        objs.append(o)
        y = o["year"]
        wl = (row.get("exam_wareki") or "").strip()
        if y not in year_labels and wl:
            year_labels[y] = wl if y > 9999 else f"{wl}（{y}年）"

    write_past_js(objs, year_labels)
    practice = load_practice_questions()
    if practice:
        write_practice_js(practice)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
