#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""宅建マスター向け 知識ハブ CSV（比較・数値・誤答）の一括リライト。"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-05-27"

COMPARE_FIELDS = [
    "slug",
    "title",
    "category",
    "tags",
    "summary",
    "col_labels",
    "compare_rows",
    "article_title",
    "article_lead",
    "exam_points",
    "common_mistakes",
    "memory_tip",
    "related_terms",
    "faq_1_question",
    "faq_1_answer",
    "faq_2_question",
    "faq_2_answer",
    "faq_3_question",
    "faq_3_answer",
    "faq_4_question",
    "faq_4_answer",
    "fact_checked_at",
]

NUMBERS_FIELDS = [
    "slug",
    "title",
    "category",
    "tags",
    "summary",
    "highlight",
    "item_rows",
    "article_title",
    "article_lead",
    "exam_points",
    "common_mistakes",
    "memory_tip",
    "related_terms",
    "faq_1_question",
    "faq_1_answer",
    "faq_2_question",
    "faq_2_answer",
    "faq_3_question",
    "faq_3_answer",
    "faq_4_question",
    "faq_4_answer",
    "fact_checked_at",
]

MISTAKES_FIELDS = [
    "slug",
    "title",
    "category",
    "tags",
    "summary",
    "confusion_point",
    "pattern_rows",
    "article_title",
    "article_lead",
    "exam_points",
    "common_mistakes",
    "memory_tip",
    "related_terms",
    "faq_1_question",
    "faq_1_answer",
    "faq_2_question",
    "faq_2_answer",
    "faq_3_question",
    "faq_3_answer",
    "faq_4_question",
    "faq_4_answer",
    "fact_checked_at",
]

COMPARISONS: list[dict] = [
    {
        "title": "35条重要事項説明と37条書面の違い",
        "category": "宅建業法",
        "tags": "35条;37条;書面",
        "summary": "契約前の説明義務と契約後の書面交付を、時期・内容・宅建士の関与で整理します。",
        "col_labels": "35条重要事項説明;37条書面",
        "compare_rows": [
            {"axis": "実施時期", "cols": ["原則として契約前", "原則として契約後5日以内"]},
            {"axis": "主な内容", "cols": ["物件・取引条件・法令制限など重要事項", "契約条項の明示（代金・引渡し・違約金等）"]},
            {"axis": "宅建士の役割", "cols": ["宅建士が説明（記名押印・交付受領証）", "書面の作成・交付（説明義務は別）"]},
            {"axis": "自ら売主の特例", "cols": ["説明期限は2日以内", "37条書面は同様に交付義務"]},
            {"axis": "試験の引っかけ", "cols": ["「契約前に37条を交付」は誤り", "「35条は契約後でよい」は誤り"]},
        ],
        "article_title": "35条重要事項説明と37条書面の違い｜宅建試験の定番整理",
        "article_lead": "宅建業法で最も問われるのが「いつ・何を・誰が」です。35条は契約前の説明、37条は契約後の書面交付が基本。順序を逆に覚えると一問落ちしやすいテーマです。",
        "exam_points": "35条＝契約前の説明・37条＝契約後の交付が骨格;宅建士は35条説明が中心;8日（35条）と5日（37条）を順序付きで暗記",
        "common_mistakes": "37条書面を契約前に交付する肢、35条説明を契約後とする肢が定番です。口頭のみで足りるとする肢にも注意。",
        "memory_tip": "「前に説明8・後に交付5」と手続の流れごと覚える。売買の流れ（説明→契約→交付）を頭に置く。",
        "related_terms": "重要事項説明（35条書面）;37条書面;35条書面;宅建士",
        "faq_1_question": "35条と37条の最大の違いは？",
        "faq_1_answer": "35条は契約前の重要事項説明、37条は契約後の契約書面の交付が基本です。",
        "faq_2_question": "説明期限の数字は？",
        "faq_2_answer": "35条説明は原則8日以内（自ら売主は2日以内）、37条書面は契約後5日以内が典型です。",
        "faq_3_question": "宅建士が必ず関与するのは？",
        "faq_3_answer": "35条重要事項説明の実施が中心です。37条は書面交付義務であり、説明義務の主体とは区別します。",
        "faq_4_question": "関連する用語はどこで確認？",
        "faq_4_answer": "本ページの比較表のあと、各用語解説記事と過去問演習で定着させるのが効率的です。",
    },
    {
        "title": "媒介契約と代理の違い",
        "category": "宅建業法",
        "tags": "媒介;代理;契約",
        "summary": "仲立ちか本人の代行かで、名義・効果・双方代理の可否が変わります。",
        "col_labels": "媒介契約;代理",
        "compare_rows": [
            {"axis": "法律上の位置づけ", "cols": ["契約の仲立ち（当事者間の契約成立を媒介）", "本人の代理人として法律行為"]},
            {"axis": "契約の名義", "cols": ["媒介者の名義で表示", "本人（本人）の名義"]},
            {"axis": "双方代理", "cols": ["原則として可能（表示等の要件あり）", "原則禁止（例外あり）"]},
            {"axis": "報酬", "cols": ["媒介報酬（定率表等）", "問題文の類型・委任とセットで確認"]},
            {"axis": "試験での典型肢", "cols": ["「代理も双方代理できる」は誤り", "「媒介は本人名義で契約」は誤り"]},
        ],
        "article_title": "媒介契約と代理の違い｜宅建試験の横並び比較",
        "article_lead": "媒介は「間に立つ」、代理は「代わりにする」。名義と双方代理の可否が試験の核心です。権利関係の代理と宅建業法の媒介を混同しないことも重要です。",
        "exam_points": "媒介＝仲立ち・代理＝代行;双方代理禁止は代理の定番;名義の違いを必ず確認",
        "common_mistakes": "媒介と代理を同じとみなし、双方代理や名義の問題で誤答しやすいです。",
        "memory_tip": "「仲立ち＝媒介・代行＝代理」。双方代理は代理の話、と切り分ける。",
        "related_terms": "媒介契約の種類;自己契約・双方代理;専任媒介契約;一般媒介契約",
        "faq_1_question": "媒介と代理の違いは？",
        "faq_1_answer": "媒介は契約成立の仲立ち、代理は本人の代理人として法律行為を行います。",
        "faq_2_question": "双方代理はどちらの話？",
        "faq_2_answer": "代理における原則禁止の制度です。媒介は原則として双方代理が可能です。",
        "faq_3_question": "名義はどう違う？",
        "faq_3_answer": "媒介は媒介者の名義で表示、代理は本人の名義で契約します。",
        "faq_4_question": "試験対策は？",
        "faq_4_answer": "比較表で差分を押さえ、過去問で「名義」「双方代理」の肢を確認してください。",
    },
    {
        "title": "専任媒介・一般媒介・専属専任の違い",
        "category": "宅建業法",
        "tags": "媒介;専任;報酬",
        "summary": "依頼の専属性・他業者への依頼可否・報酬額の違いを3列で整理します。",
        "col_labels": "専属専任媒介;専任媒介;一般媒介",
        "compare_rows": [
            {"axis": "他業者への依頼", "cols": ["他業者に依頼できない", "他業者に依頼できない", "他業者にも依頼できる"]},
            {"axis": "自己契約", "cols": ["原則としてできない", "原則としてできない", "可能（表示等）"]},
            {"axis": "報酬", "cols": ["最も高い（定率上限）", "中程度", "最も低い"]},
            {"axis": "依頼の専属性", "cols": ["最も強い", "強い", "弱い"]},
            {"axis": "試験の数字", "cols": ["1/5ルール等とセット", "専任の表示・報酬", "複数業者可能がポイント"]},
        ],
        "article_title": "専任媒介・一般媒介・専属専任の違い｜媒介契約3種",
        "article_lead": "媒介契約は依頼の専属性と報酬で整理すると取り違えにくくなります。一般だけ他業者可、専任系は自己契約制限が論点になりやすいです。",
        "exam_points": "一般のみ他業者依頼可;専任・専属は自己契約制限;報酬は専属>専任>一般が目安",
        "common_mistakes": "一般媒介でも他業者に依頼できないと答える肢、専任で自己契約自由とする肢が典型です。",
        "memory_tip": "「一般＝競合可・専任系＝独占寄り」。報酬の高低もセットで覚える。",
        "related_terms": "専属専任媒介契約;専任媒介契約;一般媒介契約;報酬の計算（売買）",
        "faq_1_question": "他業者に依頼できるのは？",
        "faq_1_answer": "一般媒介契約のみ、他の宅建業者にも依頼できます。",
        "faq_2_question": "報酬のイメージは？",
        "faq_2_answer": "専属性が強いほど報酬上限が高い傾向です。定率表で確認します。",
        "faq_3_question": "自己契約は？",
        "faq_3_answer": "専任・専属専任は原則自己契約できません。一般は可能です。",
        "faq_4_question": "試験では何が出る？",
        "faq_4_answer": "3種の違いを一肢で問う問題、報酬・表示義務と組み合わせた問題が頻出です。",
    },
    {
        "title": "普通借地権と定期借地権の違い",
        "category": "権利関係",
        "tags": "借地借家;期間",
        "summary": "存続期間・更新・正当事由の有無など、借地権の安定性の差を整理します。",
        "col_labels": "普通借地権;定期借地権",
        "compare_rows": [
            {"axis": "存続期間", "cols": ["原則30年", "50年以上（一般定期）"]},
            {"axis": "更新", "cols": ["更新が原則（正当事由なき更新拒絶は困難）", "期間満了で終了（更新なし）"]},
            {"axis": "借地人の地位", "cols": ["強い安定性", "期間限定・利用目的が明確"]},
            {"axis": "対価", "cols": ["地代の授受", "地代の授受（契約による）"]},
            {"axis": "試験の引っかけ", "cols": ["「定期も更新あり」は誤り", "「普通は50年」は誤り"]},
        ],
        "article_title": "普通借地権と定期借地権の違い｜借地借家法",
        "article_lead": "借地30年・定期50年は数字問題の定番です。更新の有無が制度の本質であり、権利関係分野の得点源になりやすいテーマです。",
        "exam_points": "普通借地30年・定期借地50年以上;普通は更新あり・定期は期間満了;正当事由は普通借地の論点",
        "common_mistakes": "存続期間を入れ替える、定期借地にも当然更新があると答える誤りが多いです。",
        "memory_tip": "「普通＝長く住み続けたい＝更新あり」「定期＝事業用・期間限定」。",
        "related_terms": "借地借家法;定期借地権・定期借家権;借地権の一体譲渡",
        "faq_1_question": "普通借地の期間は？",
        "faq_1_answer": "原則30年です（借地借家法3条）。",
        "faq_2_question": "定期借地の期間は？",
        "faq_2_answer": "一般定期借地権は50年以上が目安です。",
        "faq_3_question": "更新の違いは？",
        "faq_3_answer": "普通借地は更新が原則、定期借地は期間満了で終了します。",
        "faq_4_question": "試験頻度は？",
        "faq_4_answer": "権利関係・法令制限の両方で数字と更新の組合せが問われます。",
    },
    {
        "title": "建ぺい率と容積率の違い",
        "category": "法令上の制限",
        "tags": "建ぺい率;容積率;都市計画",
        "summary": "水平方向の占有率と垂直方向の利用強度を、算定式と用途地域とセットで整理します。",
        "col_labels": "建ぺい率;容積率",
        "compare_rows": [
            {"axis": "意味", "cols": ["敷地面積に対する建築面積の割合", "敷地面積に対する延べ面積の割合"]},
            {"axis": "見る方向", "cols": ["真上から見た占有（水平）", "立体的な利用量（垂直）"]},
            {"axis": "上限の決め方", "cols": ["用途地域ごとの建ぺい率", "用途地域ごとの容積率"]},
            {"axis": "緩和", "cols": ["角地緩和・防火地域等", "壁面後退・高さ制限等と関連"]},
            {"axis": "試験の典型", "cols": ["分子分母の取り違え", "用途地域の数値混同"]},
        ],
        "article_title": "建ぺい率と容積率の違い｜法令上の制限",
        "article_lead": "「真上から見るか」「階数を積み上げるか」の違いです。用途地域表とセットで覚えると、計算問題と肢選択の両方に効きます。",
        "exam_points": "建ぺい＝建築面積÷敷地;容積＝延べ面積÷敷地;用途地域ごとに上限が変わる",
        "common_mistakes": "建築面積と延べ面積を逆にする、角地緩和を容積率に当てはめる誤りがあります。",
        "memory_tip": "「ぺい＝平面・容積＝立体」。図を頭に描いて確認する。",
        "related_terms": "建ぺい率・容積率;容積率;用途地域の種類",
        "faq_1_question": "建ぺい率とは？",
        "faq_1_answer": "敷地面積に対する建築面積の割合です。",
        "faq_2_question": "容積率とは？",
        "faq_2_answer": "敷地面積に対する延べ面積の割合です。",
        "faq_3_question": "どちらが厳しい？",
        "faq_3_answer": "用途地域によりますが、両方とも超過すると建築できません。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "数値計算と、用途地域表の読み取りがセットで出ます。",
    },
    {
        "title": "地上権と土地賃借権の違い",
        "category": "権利関係",
        "tags": "借地;物権",
        "summary": "物権性・地代の要否・対世効力の違いを整理します。",
        "col_labels": "地上権;土地賃借権",
        "compare_rows": [
            {"axis": "性質", "cols": ["物権（対世効力あり）", "債権性の借地権"]},
            {"axis": "地代", "cols": ["地代なしでも成立し得る", "地代の授受が本質"]},
            {"axis": "設定", "cols": ["設定行為・登記", "賃貸借契約"]},
            {"axis": "普通借地との関係", "cols": ["普通借地30年の対象になり得る", "同左"]},
            {"axis": "試験の引っかけ", "cols": ["「賃借権も物権」", "「地上権は必ず地代あり」"]},
        ],
        "article_title": "地上権と土地賃借権の違い｜借地権の類型",
        "article_lead": "借地権は地上権と土地賃借権に大別されます。物権か債権か、地代が本質かが定番の引っかけです。",
        "exam_points": "地上権＝物権・地代なし可;土地賃借権＝債権・地代が本質;普通借地30年は両方に適用",
        "common_mistakes": "土地賃借権を物権とする肢、地上権に必ず地代が必要とする肢が典型です。",
        "memory_tip": "「物権地上・債権賃借」。地代なしの借地権は地上権、と結びつける。",
        "related_terms": "借地借家法;抵当権;登記",
        "faq_1_question": "地上権の性質は？",
        "faq_1_answer": "物権です。対世効力があります。",
        "faq_2_question": "土地賃借権は？",
        "faq_2_answer": "債権性の借地権で、地代の授受が本質です。",
        "faq_3_question": "地代なしの借地権は？",
        "faq_3_answer": "地上権であれば地代なしでも成立し得ます。",
        "faq_4_question": "試験対策は？",
        "faq_4_answer": "権利関係の借地権分野と、誤答パターン記事をあわせて確認してください。",
    },
    {
        "title": "手付金と定金の違い",
        "category": "権利関係",
        "tags": "手付;契約;解除",
        "summary": "手付解除・倍返しと、定金の違約金性質の違いを整理します。",
        "col_labels": "手付金;定金",
        "compare_rows": [
            {"axis": "主な機能", "cols": ["契約の担保・解除手段", "違約金・担保の機能"]},
            {"axis": "解除", "cols": ["手付放棄・倍返しで解除可能", "定金罰則（倍返し・没収）"]},
            {"axis": "上限（売買）", "cols": ["代金の20%以内（宅建実務）", "当事者の合意（上限規定は別）"]},
            {"axis": "宅建試験", "cols": ["20%・倍返しが頻出", "手付との混同問題が出る"]},
            {"axis": "引っかけ", "cols": ["「手付は違約金のみ」", "「定金は20%上限」"]},
        ],
        "article_title": "手付金と定金の違い｜権利関係・宅建",
        "article_lead": "手付は宅建業法・試験の両方で数字と解除が重要です。定金は民法の違約金制度として、手付と効果を混同しないことがポイントです。",
        "exam_points": "手付金は代金の20%上限;手付解除は倍返し;定金は違約金性質",
        "common_mistakes": "手付と定金を同じとみなし、解除効果や上限で誤答します。",
        "memory_tip": "「手付＝20%・倍返し解除」。定金は民法の「罰則」イメージ。",
        "related_terms": "手付の種類;手付金等の保全措置;手付解除",
        "faq_1_question": "手付金の上限は？",
        "faq_1_answer": "売買の手付金は代金の20%以内です。",
        "faq_2_question": "手付解除は？",
        "faq_2_answer": "手付金を放棄または倍返しして解除できます。",
        "faq_3_question": "定金との違いは？",
        "faq_3_answer": "定金は違約金の機能が中心、手付は解除手段としての側面が強いです。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "20%と倍返し、手付と定金の混同が繰り返し出題されます。",
    },
    {
        "title": "固定資産税と都市計画税の違い",
        "category": "税・その他",
        "tags": "税金;税率",
        "summary": "標準税率・納税義務者・課税標準の違いを整理します。",
        "col_labels": "固定資産税;都市計画税",
        "compare_rows": [
            {"axis": "標準税率", "cols": ["1.4%", "0.3%"]},
            {"axis": "納税義務者", "cols": ["原則として所有者", "原則として所有者"]},
            {"axis": "課税標準", "cols": ["固定資産税評価額", "固定資産税評価額（同基礎）"]},
            {"axis": "課される土地", "cols": ["市街化区域内・外を含む", "市街化区域内の土地等"]},
            {"axis": "試験の引っかけ", "cols": ["税率1.4%と0.3%の入替", "借主が納税義務者"]},
        ],
        "article_title": "固定資産税と都市計画税の違い｜税・その他",
        "article_lead": "税率1.4%と0.3%の組み合わせは税分野の鉄板です。納税義務者は原則所有者で、借主負担特約は私法上の話である点もセットで押さえます。",
        "exam_points": "固定1.4%・都市計画0.3%;納税義務者は所有者;評価額ベース",
        "common_mistakes": "税率を逆に覚える、契約の負担者と公法上の義務者を混同します。",
        "memory_tip": "「固定が太い1.4・計画が細い0.3」。",
        "related_terms": "建ぺい率・容積率;用途地域の種類",
        "faq_1_question": "標準税率は？",
        "faq_1_answer": "固定資産税1.4%、都市計画税0.3%が標準です。",
        "faq_2_question": "誰が納める？",
        "faq_2_answer": "原則として固定資産の所有者です。",
        "faq_3_question": "借主負担特約は？",
        "faq_3_answer": "私法上の負担であり、公法上の納税義務者は変わりません。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "税率の入替肢と、義務者・課税標準の肢が頻出です。",
    },
    {
        "title": "宅建試験4分野の出題配分と学習優先",
        "category": "試験対策",
        "tags": "出題;学習法",
        "summary": "権利関係・宅建業法・法令制限・税の配点と、得点戦略の目安を整理します。",
        "col_labels": "権利関係;宅建業法;法令上の制限;税・その他",
        "compare_rows": [
            {"axis": "出題目安", "cols": ["約14問", "約20問", "約8問", "約8問"]},
            {"axis": "特徴", "cols": ["民法・借地借家・判例イメージ", "業法・35条37条・報酬", "用途地域・建ぺい率・農地法", "税金・統計・その他"]},
            {"axis": "学習のコツ", "cols": ["判例・条文の読み方", "数字と手続の順序", "表と図で整理", "税率・割合の暗記"]},
            {"axis": "足切り", "cols": ["各科目7点以上必要", "同左", "同左", "同左"]},
            {"axis": "サイトでの演習", "cols": ["分野別過去問", "業法中心の一問一答", "計算・早見表", "数字の確認"]},
        ],
        "article_title": "宅建試験4分野の出題配分と学習優先｜比較表",
        "article_lead": "50問中、宅建業法が最多配点です。ただし科目別7点の足切りがあるため、偏りすぎない学習が合格の近道です。",
        "exam_points": "業法約20問が最多;全科目7点以上が必須;苦手分野は過去問で補強",
        "common_mistakes": "業法だけ勉強して権利関係を neglect すると足切りリスクがあります。",
        "memory_tip": "「権14・業20・法8・税8」のイメージで計画を立てる。",
        "related_terms": "宅建士;重要事項説明（35条書面）;建ぺい率・容積率",
        "faq_1_question": "最多配点はどの分野？",
        "faq_1_answer": "宅建業法が約20問で最多です（年度により変動あり）。",
        "faq_2_question": "足切りは？",
        "faq_2_answer": "各科目7点以上、かつ総合36点以上が必要です。",
        "faq_3_question": "学習順は？",
        "faq_3_answer": "業法と権利関係を厚めにし、法令制限・税は早見表で補強する方法が一般的です。",
        "faq_4_question": "演習は？",
        "faq_4_answer": "当サイトの過去問・一問一答で分野別に弱点を確認できます。",
    },
    {
        "title": "過去問・実践演習・一問一答の使い分け",
        "category": "試験対策",
        "tags": "演習;学習法",
        "summary": "宅建マスター内の3モードを、学習段階別に整理します。",
        "col_labels": "過去問;実践演習;一問一答",
        "compare_rows": [
            {"axis": "目的", "cols": ["出題傾向・論点の把握", "本番形式・時間配分", "短時間での知識点検"]},
            {"axis": "問題の特徴", "cols": ["年度別・本試験形式", "分野横断・50問形式", "1問が短く反復向き"]},
            {"axis": "向いている段階", "cols": ["中盤以降", "理解が進んだ後半", "初期〜直前の隙間時間"]},
            {"axis": "復習のコツ", "cols": ["解説と用語解説をリンク", "制限時間で解き直す", "間違えた用語を用語集で確認"]},
            {"axis": "サイト内の入口", "cols": ["過去問一覧", "実践演習一覧", "一問一答一覧"]},
        ],
        "article_title": "過去問・実践演習・一問一答の使い分け｜宅建マスター",
        "article_lead": "3モードは目的が異なります。一問一答で点検→過去問で論点→実践で総合力、の流れが効率的です。",
        "exam_points": "点検→論点→総合の順が基本;解説まで必ず読む;分野別弱点を記録",
        "common_mistakes": "過去問だけで時間配分の練習が不足することがあります。",
        "memory_tip": "「点検＝一問・論点＝過去問・総合＝実践」。",
        "related_terms": "宅建士;重要事項説明（35条書面）",
        "faq_1_question": "最初に使うのは？",
        "faq_1_answer": "一問一答や用語解説で基礎を固め、過去問へ進む流れが一般的です。",
        "faq_2_question": "実践演習の役割は？",
        "faq_2_answer": "本番に近い形式で時間配分と総合力を確認します。",
        "faq_3_question": "過去問の役割は？",
        "faq_3_answer": "実際の出題論点と肢の引っかけ方を把握します。",
        "faq_4_question": "どこから？",
        "faq_4_answer": "ヘッダーまたは過去問一覧のタブから各モードへ移動できます。",
    },
]

NUMBERS: list[dict] = [
    {
        "title": "宅建試験の合格点・足切り",
        "category": "試験対策",
        "tags": "合格点;足切り",
        "summary": "総合点36点以上と各科目7点以上の合格基準を早見表に整理します。",
        "highlight": "36点以上 / 各科目7点以上",
        "item_rows": [
            {"item": "合格基準（総合）", "value": "36点以上", "note": "50問満点中。1問1点"},
            {"item": "科目別足切り", "value": "各7点以上", "note": "権利・業法・法令制限・税の4科目"},
            {"item": "出題数", "value": "50問", "note": "四肢択一・120分"},
            {"item": "配点目安", "value": "権14・業20・法8・税8", "note": "年度により変動あり"},
        ],
        "article_title": "宅建試験の合格点・足切り｜数値早見表",
        "article_lead": "36点と7点×4科目は必ずセットで覚えます。総合点だけ見て科目別を neglect すると足切りで不合格になります。",
        "exam_points": "36点以上かつ各科目7点以上;50問120分;配点は業法が最多",
        "common_mistakes": "総合点だけ達成しても科目別7点未満は不合格です。",
        "memory_tip": "「36＋7×4」。模試でも科目別を必ず確認。",
        "related_terms": "宅建士;重要事項説明（35条書面）",
        "faq_1_question": "合格点は？",
        "faq_1_answer": "総合36点以上、かつ各科目7点以上です。",
        "faq_2_question": "出題数は？",
        "faq_2_answer": "50問・120分が基本形式です。",
        "faq_3_question": "最多配点は？",
        "faq_3_answer": "宅建業法が約20問で最多です。",
        "faq_4_question": "最新情報は？",
        "faq_4_answer": "RETIOの試験要項で必ず確認してください。",
    },
    {
        "title": "35条説明・37条交付・クーリングオフの期限",
        "category": "宅建業法",
        "tags": "35条;37条;期限",
        "summary": "契約前後の説明・交付とクーリングオフの代表数字を一覧化します。",
        "highlight": "35条8日 / 37条5日 / CO 8日",
        "item_rows": [
            {"item": "35条重要事項説明", "value": "原則8日以内", "note": "契約前。自ら売主は2日以内"},
            {"item": "37条書面交付", "value": "原則5日以内", "note": "契約後5日以内"},
            {"item": "クーリングオフ", "value": "8日以内", "note": "書面交付を受けた日から（対象取引）"},
            {"item": "37条契約前交付", "value": "可能", "note": "契約前交付も認められる"},
        ],
        "article_title": "35条説明・37条交付・クーリングオフの期限｜数値早見表",
        "article_lead": "8日・5日・8日は別の制度です。契約前後の順序とセットで暗記しないと取り違えます。",
        "exam_points": "35条＝契約前8日;37条＝契約後5日;CO＝8日（別制度）",
        "common_mistakes": "35条と37条の期限を逆に覚える、COを37条と混同します。",
        "memory_tip": "「前8・後5・CO8」。売買の流れに沿って覚える。",
        "related_terms": "重要事項説明（35条書面）;37条書面;クーリングオフ",
        "faq_1_question": "35条の期限は？",
        "faq_1_answer": "原則契約前8日以内です。",
        "faq_2_question": "37条は？",
        "faq_2_answer": "原則契約後5日以内の交付です。",
        "faq_3_question": "クーリングオフは？",
        "faq_3_answer": "書面交付から8日以内に無条件解除できます（対象取引）。",
        "faq_4_question": "自ら売主は？",
        "faq_4_answer": "35条説明は2日以内が目安です。",
    },
    {
        "title": "手付金・報酬の上限",
        "category": "宅建業法",
        "tags": "手付;報酬",
        "summary": "手付金20%と媒介報酬の定率上限を整理します。",
        "highlight": "手付20% / 報酬定率表",
        "item_rows": [
            {"item": "手付金上限", "value": "代金の20%以内", "note": "超過部分は無効"},
            {"item": "手付解除", "value": "倍返し", "note": "受領者が解除する場合"},
            {"item": "売買報酬上限", "value": "定率表", "note": "取引価格に応じた上限"},
            {"item": "空き家等媒介", "value": "税込33万円", "note": "800万円以下・一定条件"},
        ],
        "article_title": "手付金・報酬の上限｜数値早見表",
        "article_lead": "20%と報酬定率は業法の頻出数字です。取引価格の何%か、上限表とセットで確認します。",
        "exam_points": "手付は代金の20%;倍返し解除;報酬は定率表で算定",
        "common_mistakes": "手付を定金と混同、報酬を自由に設定できると誤認します。",
        "memory_tip": "「20%手付・倍返し」。報酬は告示の定率表。",
        "related_terms": "手付の種類;手付解除;報酬の計算（売買）",
        "faq_1_question": "手付金の上限は？",
        "faq_1_answer": "売買代金の20%以内です。",
        "faq_2_question": "手付解除は？",
        "faq_2_answer": "手付金を倍返しして解除できます。",
        "faq_3_question": "報酬は？",
        "faq_3_answer": "国土交通省告示の定率表に従い上限があります。",
        "faq_4_question": "空き家特例は？",
        "faq_4_answer": "条件を満たす場合、税込33万円上限などの特例があります。",
    },
    {
        "title": "借地借家の存続期間",
        "category": "権利関係",
        "tags": "借地;期間",
        "summary": "普通借地30年・定期50年・短期1年以下を一覧化します。",
        "highlight": "借地30年 / 定期50年 / 短期1年以下",
        "item_rows": [
            {"item": "普通借地権", "value": "30年", "note": "借地借家法3条"},
            {"item": "一般定期借地", "value": "50年以上", "note": "更新なし"},
            {"item": "普通借家（建物）", "value": "1年超", "note": "短期を除く"},
            {"item": "短期借家", "value": "1年以下", "note": "更新なし・書面等"},
        ],
        "article_title": "借地借家の存続期間｜数値早見表",
        "article_lead": "30年と50年は借地、1年超と1年以下は借家の整理です。数字だけ暗記せず更新の有無とセットで。",
        "exam_points": "普通借地30年;定期借地50年以上;短期借家1年以下",
        "common_mistakes": "借地と借家の年数を入れ替える誤りが典型です。",
        "memory_tip": "「地30・定期50・家1超・短期1以下」。",
        "related_terms": "借地借家法;定期借地権・定期借家権",
        "faq_1_question": "普通借地は？",
        "faq_1_answer": "原則30年です。",
        "faq_2_question": "定期借地は？",
        "faq_2_answer": "50年以上が目安です。",
        "faq_3_question": "短期借家は？",
        "faq_3_answer": "1年以下で更新がありません。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "権利関係で数字と更新の組合せが頻出です。",
    },
    {
        "title": "成年・保佐・後見の年齢",
        "category": "権利関係",
        "tags": "成年;行為能力",
        "summary": "成年18歳と保護制度の開始年齢を整理します。",
        "highlight": "成年18歳 / 保佐17歳から",
        "item_rows": [
            {"item": "成年", "value": "18歳", "note": "2022年4月改正"},
            {"item": "未成年", "value": "18歳未満", "note": "旧基準20歳の肢に注意"},
            {"item": "保佐開始", "value": "17歳から", "note": "保佐開始の申立て等"},
            {"item": "後見", "value": "制限最強", "note": "後見>保佐>補助"},
        ],
        "article_title": "成年・保佐・後見の年齢｜数値早見表",
        "article_lead": "成年18歳への改正後も、20歳の肢が残ることがあります。最新の民法年齢を優先します。",
        "exam_points": "成年18歳;17歳から保佐;行為能力は後見>保佐>補助",
        "common_mistakes": "成年を20歳のまま暗記していると即不正解です。",
        "memory_tip": "「18成年・17保佐・制限は後>保>補」。",
        "related_terms": "意思表示;自己契約・双方代理",
        "faq_1_question": "成年年齢は？",
        "faq_1_answer": "18歳です。",
        "faq_2_question": "20歳の肢は？",
        "faq_2_answer": "改正前の基準です。",
        "faq_3_question": "保佐は？",
        "faq_3_answer": "17歳から保佐開始の申立てが可能です。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "行為能力と契約効力の問題で出ます。",
    },
    {
        "title": "固定資産税・都市計画税の税率",
        "category": "税・その他",
        "tags": "税金;税率",
        "summary": "標準税率1.4%と0.3%を早見表に整理します。",
        "highlight": "固定1.4% / 都市計画0.3%",
        "item_rows": [
            {"item": "固定資産税（標準）", "value": "1.4%", "note": "評価額に対する"},
            {"item": "都市計画税（標準）", "value": "0.3%", "note": "市街化区域内等"},
            {"item": "納税義務者", "value": "原則所有者", "note": "借主負担特約は別"},
            {"item": "課税標準", "value": "固定資産税評価額", "note": "取引価格ではない"},
        ],
        "article_title": "固定資産税・都市計画税の税率｜数値早見表",
        "article_lead": "1.4%と0.3%の入替が最頻出の引っかけです。義務者は原則所有者とセットで覚えます。",
        "exam_points": "固定1.4%・都市計画0.3%;納税義務者は所有者;評価額ベース",
        "common_mistakes": "税率逆転、借主が義務者と答える誤り。",
        "memory_tip": "「固定が太い1.4・計画が細い0.3」。",
        "related_terms": "建ぺい率・容積率",
        "faq_1_question": "標準税率は？",
        "faq_1_answer": "固定資産税1.4%、都市計画税0.3%です。",
        "faq_2_question": "誰が納める？",
        "faq_2_answer": "原則固定資産の所有者です。",
        "faq_3_question": "借主負担は？",
        "faq_3_answer": "契約上の負担であり、公法上の義務者は変わりません。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "税率と義務者の肢がセットで出ます。",
    },
    {
        "title": "用途地域の建ぺい率・容積率（代表値）",
        "category": "法令上の制限",
        "tags": "用途地域;建ぺい率",
        "summary": "主要用途地域の建ぺい率・容積率の代表値を一覧化します。",
        "highlight": "一低60/200・商業80/400 等",
        "item_rows": [
            {"item": "第一種低層住居", "value": "60% / 200%", "note": "建ぺい/容積"},
            {"item": "第一種住居", "value": "60% / 200%", "note": "代表値。防火地域で緩和"},
            {"item": "近隣商業", "value": "80% / 400%", "note": "商業系の入口"},
            {"item": "商業地域", "value": "80% / 400%", "note": "建ぺい率は80%が目安"},
        ],
        "article_title": "用途地域の建ぺい率・容積率｜数値早見表",
        "article_lead": "用途地域表は法令制限の得点源です。代表値を押さえ、角地緩和・防火地域は別途確認します。",
        "exam_points": "低層・住居は60/200が目安;商業系は80/400;緩和規定は別問題",
        "common_mistakes": "用途地域ごとの数値を混同、建ぺいと容積の分子分母を逆にする。",
        "memory_tip": "「低層60/200・商業80/400」から覚え、表全体は過去問で補強。",
        "related_terms": "建ぺい率・容積率;用途地域の種類;容積率",
        "faq_1_question": "一低の目安は？",
        "faq_1_answer": "建ぺい率60%、容積率200%が代表値です。",
        "faq_2_question": "商業地域は？",
        "faq_2_answer": "80%/400%が典型です。",
        "faq_3_question": "角地緩和は？",
        "faq_3_answer": "建ぺい率に10%加算など、別規定です。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "表読みと計算問題の両方が出ます。",
    },
    {
        "title": "宅建業法の罰則・過料（代表）",
        "category": "宅建業法",
        "tags": "罰則;過料",
        "summary": "重要事項説明違反等の代表罰則を早見表に整理します。",
        "highlight": "100万円以下 / 3年以下 等",
        "item_rows": [
            {"item": "35条説明違反", "value": "100万円以下", "note": "過料。宅建士・業者"},
            {"item": "37条書面不交付", "value": "100万円以下", "note": "過料"},
            {"item": "免許不正", "value": "3年以下懲役等", "note": "問題文で条文確認"},
            {"item": "指示処分", "value": "業務停止等", "note": "監督処分は別枠"},
        ],
        "article_title": "宅建業法の罰則・過料｜数値早見表",
        "article_lead": "100万円以下の過料は35条・37条違反で頻出です。刑事罰と過料・監督処分を混同しないこと。",
        "exam_points": "35条37条違反は100万円以下が典型;免許不正は刑事;監督処分は別",
        "common_mistakes": "過料と懲役刑を逆にする、業務停止を過料と混同。",
        "memory_tip": "「説明・交付ミス＝100万以下過料」をまず固定。",
        "related_terms": "重要事項説明（35条書面）;37条書面;宅建士",
        "faq_1_question": "35条違反の過料は？",
        "faq_1_answer": "100万円以下が典型です。",
        "faq_2_question": "37条は？",
        "faq_2_answer": "同様に100万円以下の過料が問われます。",
        "faq_3_question": "試験では？",
        "faq_3_answer": "数字と違反類型の組合せが出ます。",
        "faq_4_question": "最新は？",
        "faq_4_answer": "条文・告示で必ず確認してください。",
    },
    {
        "title": "登記・相続登記の期限",
        "category": "権利関係",
        "tags": "登記;相続",
        "summary": "相続登記3年など手続期限の代表値を整理します。",
        "highlight": "相続登記3年 / 抵当権設定は速やか",
        "item_rows": [
            {"item": "相続登記", "value": "知った日から3年", "note": "申請期限の一般論"},
            {"item": "抵当権設定", "value": "契約後速やか", "note": "問題文の表現に注意"},
            {"item": "登記の効力", "value": "対抗要件", "note": "第三者対抗力"},
            {"item": "2024年相続登記", "value": "義務化・過料", "note": "制度改正を要確認"},
        ],
        "article_title": "登記・相続登記の期限｜数値早見表",
        "article_lead": "相続登記3年は権利関係の定番数字です。近年の義務化・過料も試験に反映されるため公式情報で確認を。",
        "exam_points": "相続登記3年;登記は対抗要件;抵当権は設定登記",
        "common_mistakes": "異なる登記の期限を1つに混同する。",
        "memory_tip": "手続名ごとに「誰が・いつまで」を分けて覚える。",
        "related_terms": "抵当権;登記",
        "faq_1_question": "相続登記の期限は？",
        "faq_1_answer": "相続を知った日から3年が典型です。",
        "faq_2_question": "抵当権は？",
        "faq_2_answer": "設定契約後速やかに申請が原則です。",
        "faq_3_question": "義務化は？",
        "faq_3_answer": "相続登記の義務化・過料規定は最新法令で確認してください。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "3年と対抗要件がセットで出やすいです。",
    },
    {
        "title": "専任媒介の制限・報告",
        "category": "宅建業法",
        "tags": "専任;媒介",
        "summary": "専任媒介の1/5ルールと定期報告14日などを整理します。",
        "highlight": "1/5ルール / 14日報告",
        "item_rows": [
            {"item": "他業者への依頼", "value": "原則不可", "note": "専任・専属専任"},
            {"item": "1/5ルール", "value": "依頼者の同意", "note": "一定割合超の依頼等"},
            {"item": "定期報告", "value": "14日ごと", "note": "媒介契約の報告義務"},
            {"item": "有効期間", "value": "3か月", "note": "専任媒介の上限（延長可）"},
        ],
        "article_title": "専任媒介の制限・報告｜数値早見表",
        "article_lead": "14日報告と3か月有効期間は専任媒介の頻出数字です。一般媒介との違いとセットで確認します。",
        "exam_points": "専任は他業者不可;14日ごと報告;有効期間3か月",
        "common_mistakes": "一般媒介にも14日報告が必要と誤認。",
        "memory_tip": "「専任＝14日報告・3か月」。",
        "related_terms": "専任媒介契約;一般媒介契約;定期報告（媒介）",
        "faq_1_question": "定期報告は？",
        "faq_1_answer": "14日ごとが目安です。",
        "faq_2_question": "有効期間は？",
        "faq_2_answer": "3か月が上限（延長可能）です。",
        "faq_3_question": "他業者依頼は？",
        "faq_3_answer": "専任・専属専任は原則不可です。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "媒介3種との違いと数字がセットで出ます。",
    },
]

MISTAKES: list[dict] = [
    {
        "title": "35条説明と37条書面の取り違え",
        "category": "宅建業法",
        "tags": "35条;37条",
        "summary": "契約前後の順序を逆に選ぶ定番パターン。",
        "confusion_point": "契約前後の順序",
        "pattern_rows": [
            {"topic": "実施時期", "wrong": "37条書面は契約前に交付", "correct": "35条説明は契約前、37条は原則契約後5日以内", "trap": "説明と交付の順序"},
            {"topic": "宅建士", "wrong": "37条も宅建士が説明", "correct": "35条説明は宅建士、37条は書面交付義務", "trap": "説明義務の混同"},
            {"topic": "口頭", "wrong": "口頭のみで足りる", "correct": "書面または電磁的方法が必要", "trap": "口頭のみOK"},
        ],
        "article_title": "35条説明と37条書面の取り違え｜誤答パターン",
        "article_lead": "業法最大の引っかけの一つ。前35・後37を逆にするとほぼ確実に不正解です。",
        "exam_points": "35条＝契約前;37条＝契約後;宅建士は35条説明",
        "common_mistakes": "37条を契約前、35条を契約後とする肢。",
        "memory_tip": "「前に35・後に37」。",
        "related_terms": "重要事項説明（35条書面）;37条書面;35条書面",
        "faq_1_question": "典型誤答は？",
        "faq_1_answer": "37条書面を契約前に交付する肢です。",
        "faq_2_question": "正しい順序は？",
        "faq_2_answer": "35条説明→契約→37条交付です。",
        "faq_3_question": "数字は？",
        "faq_3_answer": "8日（35条）と5日（37条）を順序付きで。",
        "faq_4_question": "対策は？",
        "faq_4_answer": "比較表と過去問で反復確認してください。",
    },
    {
        "title": "媒介と代理の混同",
        "category": "宅建業法",
        "tags": "媒介;代理",
        "summary": "双方代理と名義の取り違え。",
        "confusion_point": "双方代理可否",
        "pattern_rows": [
            {"topic": "双方代理", "wrong": "媒介も双方代理禁止", "correct": "代理は禁止、媒介は原則可能", "trap": "双方代理の可否"},
            {"topic": "名義", "wrong": "媒介も本人名義", "correct": "媒介は媒介者名義、代理は本人名義", "trap": "名義の違い"},
            {"topic": "報酬", "wrong": "代理は報酬なし", "correct": "類型と報酬は別。問題文確認", "trap": "固定観念"},
        ],
        "article_title": "媒介と代理の混同｜誤答パターン",
        "article_lead": "仲立ちと代行の混同は業法・権利関係の両方で出ます。",
        "exam_points": "代理＝双方代理禁止;媒介＝仲立ち",
        "common_mistakes": "媒介に双方代理禁止を当てはめる。",
        "memory_tip": "「双方代理は代理の話」。",
        "related_terms": "媒介契約の種類;自己契約・双方代理",
        "faq_1_question": "典型肢は？",
        "faq_1_answer": "媒介も双方代理できない、という肢です。",
        "faq_2_question": "名義は？",
        "faq_2_answer": "媒介は媒介者、代理は本人名義です。",
        "faq_3_question": "試験頻度は？",
        "faq_3_answer": "業法で毎年級の出題があります。",
        "faq_4_question": "関連記事は？",
        "faq_4_answer": "比較表「媒介契約と代理の違い」も参照してください。",
    },
    {
        "title": "地上権と土地賃借権の混同",
        "category": "権利関係",
        "tags": "借地;物権",
        "summary": "物権性と地代の要否。",
        "confusion_point": "物権・地代",
        "pattern_rows": [
            {"topic": "物権性", "wrong": "土地賃借権も物権", "correct": "地上権は物権、土地賃借権は債権性", "trap": "物権性"},
            {"topic": "地代", "wrong": "地上権も地代必須", "correct": "地上権は地代なし可、賃借権は地代が本質", "trap": "地代の要否"},
            {"topic": "期間", "wrong": "地上権は1年超", "correct": "普通借地30年は両方に適用", "trap": "期間規定"},
        ],
        "article_title": "地上権と土地賃借権の混同｜誤答パターン",
        "article_lead": "借地権分野の定番。物権か債権かで肢を切り分けます。",
        "exam_points": "地上権＝物権;賃借権＝債権",
        "common_mistakes": "賃借権を物権とする。",
        "memory_tip": "「物権地上・債権賃借」。",
        "related_terms": "借地借家法;抵当権",
        "faq_1_question": "典型誤答は？",
        "faq_1_answer": "土地賃借権を物権とする肢です。",
        "faq_2_question": "地代なしは？",
        "faq_2_answer": "地上権で成立し得ます。",
        "faq_3_question": "30年は？",
        "faq_3_answer": "普通借地権の存続期間です。",
        "faq_4_question": "対策は？",
        "faq_4_answer": "比較表と過去問で確認してください。",
    },
    {
        "title": "先取特権の順位",
        "category": "権利関係",
        "tags": "先取;担保",
        "summary": "一般先取を最優先と誤るパターン。",
        "confusion_point": "法定先取順位",
        "pattern_rows": [
            {"topic": "不動産", "wrong": "一般先取が最優先", "correct": "不動産先取特権が最優先", "trap": "目的物別順位"},
            {"topic": "動産", "wrong": "不動産先取が動産にも", "correct": "動産先取特権が最優先", "trap": "適用対象"},
            {"topic": "一般先取", "wrong": "常に第1順位", "correct": "一般先取は最後", "trap": "一般先取の位置"},
        ],
        "article_title": "先取特権の順位｜誤答パターン",
        "article_lead": "目的物ごとに順位が変わります。一般先取が最優先ではありません。",
        "exam_points": "不動産＝不動産先取;動産＝動産先取;一般は最後",
        "common_mistakes": "一般先取を常に第1順位とする。",
        "memory_tip": "「不動産不・動産動・一般最後」。",
        "related_terms": "質権・先取特権・留置権;抵当権",
        "faq_1_question": "不動産は？",
        "faq_1_answer": "不動産先取特権が最優先です。",
        "faq_2_question": "動産は？",
        "faq_2_answer": "動産先取特権が最優先です。",
        "faq_3_question": "一般先取は？",
        "faq_3_answer": "他の先取の後です。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "順位問題が権利関係で頻出です。",
    },
    {
        "title": "固定資産税と都市計画税の混同",
        "category": "税・その他",
        "tags": "税金",
        "summary": "税率1.4%と0.3%の入替。",
        "confusion_point": "税率",
        "pattern_rows": [
            {"topic": "税率", "wrong": "都市計画税1.4%", "correct": "固定1.4%、都市計画0.3%", "trap": "入替"},
            {"topic": "義務者", "wrong": "借主が納税義務者", "correct": "原則所有者", "trap": "私法と公法"},
            {"topic": "課税標準", "wrong": "取引価格", "correct": "固定資産税評価額", "trap": "評価額"},
        ],
        "article_title": "固定資産税と都市計画税の混同｜誤答パターン",
        "article_lead": "税分野の鉄板引っかけ。数字と義務者をセットで確認。",
        "exam_points": "1.4%と0.3%;所有者が義務者",
        "common_mistakes": "税率逆転。",
        "memory_tip": "「固定1.4・計画0.3」。",
        "related_terms": "建ぺい率・容積率",
        "faq_1_question": "典型肢は？",
        "faq_1_answer": "税率を入れ替えた肢です。",
        "faq_2_question": "義務者は？",
        "faq_2_answer": "原則所有者です。",
        "faq_3_question": "借主負担は？",
        "faq_3_answer": "契約上の話であり義務者は変わりません。",
        "faq_4_question": "早見表は？",
        "faq_4_answer": "数値早見表もあわせて確認してください。",
    },
    {
        "title": "クーリングオフと手付解除の混同",
        "category": "宅建業法",
        "tags": "解除;手付",
        "summary": "無条件解除と倍返しの混同。",
        "confusion_point": "解除効果",
        "pattern_rows": [
            {"topic": "CO", "wrong": "手付倍返しが必要", "correct": "書面で無条件解除（対象取引）", "trap": "対価返還"},
            {"topic": "手付", "wrong": "相手同意が必要", "correct": "手付放棄・倍返しで解除", "trap": "解除要件"},
            {"topic": "期間", "wrong": "手付も8日", "correct": "COは8日（対象取引）", "trap": "期間"},
        ],
        "article_title": "クーリングオフと手付解除の混同｜誤答パターン",
        "article_lead": "COは無条件、手付は倍返し。効果を混同しないこと。",
        "exam_points": "CO＝無条件;手付＝倍返し",
        "common_mistakes": "手付解除にCOの無条件性を当てはめる。",
        "memory_tip": "「無条件CO・手付倍返し」。",
        "related_terms": "クーリングオフ;手付解除;手付の種類",
        "faq_1_question": "COの効果は？",
        "faq_1_answer": "無条件に解除できます。",
        "faq_2_question": "手付解除は？",
        "faq_2_answer": "手付金を倍返しまたは放棄します。",
        "faq_3_question": "8日は？",
        "faq_3_answer": "クーリングオフの典型期間です。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "解除効果の肢選択が頻出です。",
    },
    {
        "title": "建ぺい率と容積率の計算ミス",
        "category": "法令上の制限",
        "tags": "建ぺい率;容積率",
        "summary": "分子分母の取り違え。",
        "confusion_point": "算定式",
        "pattern_rows": [
            {"topic": "建ぺい率", "wrong": "延べ面積÷敷地", "correct": "建築面積÷敷地", "trap": "分子"},
            {"topic": "容積率", "wrong": "建築面積÷敷地", "correct": "延べ面積÷敷地", "trap": "分子"},
            {"topic": "緩和", "wrong": "容積率に角地緩和", "correct": "建ぺい率に角地緩和等", "trap": "緩和規定"},
        ],
        "article_title": "建ぺい率と容積率の計算ミス｜誤答パターン",
        "article_lead": "計算問題は分子の取り違えが主因。平面と立体を意識して解く。",
        "exam_points": "建ぺい＝建築面積;容積＝延べ面積",
        "common_mistakes": "分子分母逆転。",
        "memory_tip": "「ぺい＝平面・容積＝立体」。",
        "related_terms": "建ぺい率・容積率;容積率;用途地域の種類",
        "faq_1_question": "典型ミスは？",
        "faq_1_answer": "建築面積と延べ面積を逆にします。",
        "faq_2_question": "角地緩和は？",
        "faq_2_answer": "主に建ぺい率に適用されます。",
        "faq_3_question": "試験では？",
        "faq_3_answer": "計算問題と肢選択の両方があります。",
        "faq_4_question": "比較表は？",
        "faq_4_answer": "建ぺい率と容積率の比較記事も参照してください。",
    },
    {
        "title": "専任媒介と一般媒介の取り違え",
        "category": "宅建業法",
        "tags": "媒介;専任",
        "summary": "他業者依頼可否の誤答。",
        "confusion_point": "他業者依頼",
        "pattern_rows": [
            {"topic": "他業者", "wrong": "一般も他業者不可", "correct": "一般のみ他業者可", "trap": "依頼可否"},
            {"topic": "自己契約", "wrong": "専任も自由", "correct": "専任・専属は原則不可", "trap": "自己契約"},
            {"topic": "報告", "wrong": "一般も14日報告", "correct": "専任系の報告義務", "trap": "報告義務"},
        ],
        "article_title": "専任媒介と一般媒介の取り違え｜誤答パターン",
        "article_lead": "一般だけ他業者可、が最大の差分です。",
        "exam_points": "一般＝他業者可;専任＝他業者不可",
        "common_mistakes": "一般媒介でも他業者不可と答える。",
        "memory_tip": "「一般だけ競合可」。",
        "related_terms": "専任媒介契約;一般媒介契約;専属専任媒介契約",
        "faq_1_question": "典型誤答は？",
        "faq_1_answer": "一般媒介でも他業者に依頼できないとする肢です。",
        "faq_2_question": "報告義務は？",
        "faq_2_answer": "専任系に14日報告等があります。",
        "faq_3_question": "比較表は？",
        "faq_3_answer": "媒介3種の比較記事を参照してください。",
        "faq_4_question": "試験では？",
        "faq_4_answer": "媒介契約の種類問題で頻出です。",
    },
    {
        "title": "成年18歳と旧20歳の引っかけ",
        "category": "権利関係",
        "tags": "成年;民法改正",
        "summary": "2022年改正後も20歳の肢が残る。",
        "confusion_point": "成年年齢",
        "pattern_rows": [
            {"topic": "成年", "wrong": "20歳", "correct": "18歳（2022年4月〜）", "trap": "旧基準"},
            {"topic": "契約", "wrong": "17歳も単独有効", "correct": "未成年は取消可能等", "trap": "行為能力"},
            {"topic": "保佐", "wrong": "18歳から", "correct": "17歳から保佐開始", "trap": "年齢混同"},
        ],
        "article_title": "成年18歳と旧20歳の引っかけ｜誤答パターン",
        "article_lead": "民法改正は毎年級の出題テーマ。18歳を優先します。",
        "exam_points": "成年18歳;17歳保佐;20歳肢は旧",
        "common_mistakes": "20歳を成年と答える。",
        "memory_tip": "「2022から18」。",
        "related_terms": "意思表示;自己契約・双方代理",
        "faq_1_question": "成年は？",
        "faq_1_answer": "18歳です。",
        "faq_2_question": "20歳の肢は？",
        "faq_2_answer": "改正前の引っかけです。",
        "faq_3_question": "試験では？",
        "faq_3_answer": "行為能力問題で頻出です。",
        "faq_4_question": "早見表は？",
        "faq_4_answer": "数値早見表「成年・保佐・後見」も参照してください。",
    },
    {
        "title": "宅建士と免許の混同",
        "category": "宅建業法",
        "tags": "宅建士;免許",
        "summary": "個人資格と法人免許の混同。",
        "confusion_point": "資格と免許",
        "pattern_rows": [
            {"topic": "主体", "wrong": "宅建士が免許を受ける", "correct": "免許は法人・個人業者、宅建士は資格", "trap": "主体"},
            {"topic": "35条", "wrong": "免許者が説明", "correct": "宅建士が重要事項説明", "trap": "説明義務者"},
            {"topic": "変更", "wrong": "宅建士変更届のみ", "correct": "専任宅建士変更届等", "trap": "届出"},
        ],
        "article_title": "宅建士と免許の混同｜誤答パターン",
        "article_lead": "宅建士は資格、宅建業免許は事業者の許認可です。35条説明は宅建士が実施します。",
        "exam_points": "宅建士＝資格;免許＝事業者;35条は宅建士",
        "common_mistakes": "宅建士が免許を持つと誤認。",
        "memory_tip": "「士＝資格・業＝免許」。",
        "related_terms": "宅建士;宅建士資格登録簿",
        "faq_1_question": "典型誤答は？",
        "faq_1_answer": "宅建士が宅建業免許を受ける、という肢です。",
        "faq_2_question": "35条は？",
        "faq_2_answer": "宅建士が説明します。",
        "faq_3_question": "試験では？",
        "faq_3_answer": "業法の主体問題で出ます。",
        "faq_4_question": "用語解説は？",
        "faq_4_answer": "「宅建士」の用語記事も参照してください。",
    },
]

# 得点源（S）に設定する用語（部分一致）
S_TERM_KEYS = [
    "重要事項説明",
    "35条書面",
    "37条書面",
    "契約書の作成・交付",
    "媒介契約",
    "専任媒介",
    "専属専任",
    "一般媒介",
    "手付",
    "クーリングオフ",
    "宅建士",
    "報酬",
    "建ぺい率",
    "容積率",
    "用途地域",
    "抵当権",
    "借地借家",
    "定期借地",
    "自己契約",
    "双方代理",
    "固定資産税",
    "都市計画",
    "農地法",
    "都市計画法",
    "建築基準法",
    "登記",
    "意思表示",
    "先取特権",
    "質権",
    "根抵当",
    "35条",
    "37条",
    "業務規程",
    "重要事項の不告知",
    "37条書面",
]


def _json_field(rows: list) -> str:
    return json.dumps(rows, ensure_ascii=False)


def _row_base(d: dict) -> dict:
    d = dict(d)
    d["slug"] = ""
    d["fact_checked_at"] = DATE
    return d


def write_csv(path: Path, fields: list[str], rows: list[dict], json_keys: list[str]) -> None:
    out: list[dict] = []
    for raw in rows:
        row = _row_base(raw)
        for key in json_keys:
            if key in row and not isinstance(row[key], str):
                row[key] = _json_field(row[key])
        out.append({f: row.get(f, "") for f in fields})
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        w.writeheader()
        w.writerows(out)


def update_glossary_importance() -> tuple[int, int]:
    path = ROOT / "data" / "glossary_terms.csv"
    text = path.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    fieldnames = rows[0].keys() if rows else []
    if "importance" not in fieldnames:
        raise SystemExit("glossary_terms.csv に importance 列がありません")
    n_s = n_a = 0
    for row in rows:
        term = row.get("term") or ""
        if any(k in term for k in S_TERM_KEYS):
            row["importance"] = "S"
            n_s += 1
        else:
            row["importance"] = "A"
            n_a += 1
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    return n_s, n_a


def main() -> int:
    write_csv(ROOT / "data" / "comparisons.csv", COMPARE_FIELDS, COMPARISONS, ["compare_rows"])
    write_csv(ROOT / "data" / "numbers.csv", NUMBERS_FIELDS, NUMBERS, ["item_rows"])
    write_csv(ROOT / "data" / "mistakes.csv", MISTAKES_FIELDS, MISTAKES, ["pattern_rows"])
    n_s, n_a = update_glossary_importance()
    print(f"Wrote {len(COMPARISONS)} comparisons, {len(NUMBERS)} numbers, {len(MISTAKES)} mistakes")
    print(f"Glossary importance: S={n_s}, A={n_a}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
